netneurolab/netneurotools

- netneurotools/modularity.py
Previously the code for `consensus_modularity()` returned a float array for the community assignments, which is silly and also caused `plot_mod_heatmap()` to break. This PR fixes that issue!
> [FIX] Consensus modularity returns int array

- .travis.yml
- netneurotools/networks.py
Previously bootstrapping in func_consensus() was handled...poorly. This
attempts to ~half the amount of memory consumed by only performing
operations on the upper triangle!
> [REF] Better memory handling in func_consensus()

- docs/api.rst
- netneurotools/tests/test_datasets.py
- netneurotools/tests/test_metrics.py
- netneurotools/tests/test_modularity.py
- netneurotools/tests/test_utils.py
- netneurotools/utils.py
Small wrapper for scipy.ndimage.center_of_mass() to enable easy centroid calculation for neuroimaging atlases.
> [ENH] Adds utils.get_centroids() function

- netneurotools/datasets/datasets.py
- netneurotools/datasets/utils.py
- netneurotools/freesurfer.py
- netneurotools/plotting.py
- netneurotools/tests/test_datasets.py
- resources/generate_atl-cammoun2012_surface.py
Previous surface .annot files for the Cammoun 2012 parcellation were out-of-sync with the volumetric images. This fixes them and addresses a whole bunch of other changes that were resolved in the processing of that fix.
> [REF] Fixes Cammoun et al., 2012 Freesurfer files

- examples/plot_mirchi_2018.py
- netneurotools/info.py
Or at least, tries to reduce memory consumption... It was causing the ReadTheDocs build to fail because of excessive memory usage, so this deletes some large intermediate arrays that might help keep the load low.
> [REF] Reduces memory consumption in Mirchi et al., 2018 example

- netneurotools/freesurfer.py
- netneurotools/tests/test_freesurfer.py
Assuming users have a FreeSurfer-style annotation file with parcellation information, adds functions for projecting parcellated data to vertices and reducing vertex-level data to parcels.
> [ENH] Adds parcellation projection to/reduction from FreeSurfer vertices

- examples/plot_spin_test.py
- netneurotools/stats.py
- netneurotools/tests/test_stats.py
Also adds some (super basic) tests for the function :tada:
Removes need to calculate full distance matrix to reassign coordinates during rotations, instead opting to use cKDTree for efficient nearest-neighbor lookup. Also adds a new parameter, `check_duplicates`, that allows users to turn off any warnings that might arise from perfectly duplicate spins / reassignments (which can, with very large inputs, be quite time consuming).
To Do:
> [REF] Updates gen_spinsamples for efficiency

- docs/api.rst
- netneurotools/data/osf.json
- netneurotools/datasets/__init__.py
- netneurotools/datasets/fetchers.py
- netneurotools/datasets/generators.py
- netneurotools/datasets/utils.py
- netneurotools/tests/test_datasets.py
**ENH**: Adds a `fetch_connectome()` function for getting species-specific structural/functional connectivity matrices.
**REF**: Separates dataset fetchers from dataset generators and moves former `OSF_RESOURCES` dictionary into `data/osf.json` for easier maintenance.
To Do:
> [REF, ENH] Refactors `nntools.datasets` module

- netneurotools/freesurfer.py
- netneurotools/tests/test_freesurfer.py
When names in `drop` parameter weren't present in provided annotation files the function(s) would errored; this is now resolved.
Also adds a new parcel to drop by default commonly found in CBIG parcellations (`'Background+FreeSurfer_Defined_Medial_Wall'`).
> [FIX] Fixes parcel dropping in nntools.freesurfer

- netneurotools/plotting.py
Requires nipy/pysurfer@dd9f3b5 (or newer).
Also, modify `site-packages/vtkmodules/qt/__init__.py` file and make this change:
```diff
-QVTKRWIBase = "QWidget"
+QVTKRWIBase = "QGLWidget"
```
and modify `site-packages/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py` and make this change:
```diff
if PyQtImpl == "PyQt5":
if QVTKRWIBase == "QGLWidget":
-        try:
-            from PyQt5.QtWidgets import QOpenGLWidget as QGLWidget
-        except:
-            from PyQt5.QtOpenGL import QGLWidget
+       from PyQt5.QtOpenGL import QGLWidget
```
Make sure you have `vtk>=8.2` and `pyqt>=5.9.2` installed. Now you shouldn't get weird speckling when plotting with `nnplot.plot_fsaverage()`!
> [FIX] Fixes pysurfer opacity bug

- netneurotools/stats.py
- netneurotools/tests/test_stats.py
Pre-generates kdtrees for computational efficiency. Also reverse matching of rotated --> original to original --> rotated for ease of use.
> [FIX] Minor change to spin sample generation

- netneurotools/networks.py
Changed np.mean() to np.nanmean() in func_consensus() function, when the consensus matrix is computed without any bootstrap.
This change is useful for a few cases where an individual subject has no BOLD signal data for an individual node (0s at every time point). When this happen, you don't want to completely ignore the subject, but you want to ignore the NaN correlations that np.corrcoef will return for pairwise correlations with this node. 
Example: Subject 39, node 113 in func_scale500.npy file
> [FIX] np.nanmean in func consensus when no boot

- netneurotools/networks.py
Added what I understand to be the *recommended* way to turn binary structural consensus maps into weighted maps, based on conversation with @rmarkello. The default value for the flag is `false`, so this addition won't change current behaviour.
(Please let me know if there were tests for this function that I should update, as well, but my quick `git grep` didn't find any).
Thanks!
> Added weight option for struct consensus

- netneurotools/stats.py
- netneurotools/tests/test_stats.py
Closes #86.
Title is relatively self-explanatory, but now you can provide coordinates for a single hemisphere and `netneurotools.stats.gen_spinsamples()` doesn't fail. Tests are updated to match.
> [ENH] Allows spins with only one hemisphere 

- netneurotools/freesurfer.py
- netneurotools/tests/test_freesurfer.py
Closes #84.
Allows integer inputs to `netneurotools.freesurfer.parcels_to_vertices()`. Previously this would error due to the insertion of `np.nan` for "ignored" parcels (e.g., corpus callosum, medial wall).
> [REF] Allow integer inputs in `freesurfer.parcels_to_vertices()`

- docs/api.rst
- netneurotools/civet.py
- netneurotools/data/osf.json
- netneurotools/datasets/__init__.py
- netneurotools/datasets/fetchers.py
- netneurotools/tests/test_civet.py
- netneurotools/tests/test_datasets.py
Also adds a fetcher for the CIVET surfaces and a CIVET surface reader function.
We should be able to use this to map the CIVET-space stat maps to `fsaverage6` space pretty easily @justinehansen @liuzhenqi77 ! I checked with the glycolytic index maps @justinehansen had provided me and this returns identical results to the Matlab script :grin:
To Do:
> [ENH] Adds function to map CIVET to FreeSurfer

- netneurotools/plotting.py
- requirements.txt
- tools/install_dependencies.sh
The function plot_point_brain() sets the limits of the xyz axes with the following lines of code:
`        ax.set(xlim=0.57 * np.array(ax.get_xlim()),
ylim=0.57 * np.array(ax.get_ylim()),
zlim=0.60 * np.array(ax.get_zlim()))`
It also zscores the coordinates beforehand.
This might be problematic since these limits, being hard-coded, can lead to various bugs. For instance, if we use the coordinates of the Lausanne 1000 parcellation, some parcels are cropped out:
To solve this particular bug, I modified those lines to 
`                ax.set(xlim=0.665 * np.array(ax.get_xlim()),
ylim=0.665 * np.array(ax.get_ylim()),
zlim=0.70 * np.array(ax.get_zlim()))`.
We now get this when we try to plot the Lausanne 1000 parcellation:
The parcels are no longer cropped out.
Also, I personally enjoy …
> Add custom_aspect parameter to plot_point_brain.

- netneurotools/freesurfer.py
- netneurotools/stats.py
This pull request fixes the import statements for functions in private namespaces in scipy. Private namespaces where renamed in scipy 1.8.0 to distinguish them from public ones (see [this issue](https://github.com/scipy/scipy/issues/14360)). I fixed the import statements appropriately and used a try/except statement so that the toolbox still works with scipy < 1.8.0
> [MNT] Import private namespaces if scipy > 1.8.0

- .github/workflows/tests.yml
- netneurotools/datasets/utils.py
Since `pkg_resources ` is going to be removed in Python 3.12, replacing it with `importlib.resources.files`. Currently it is not a perfect solution because `importlib.resources` is also undergoing substantial changes across version.
> [FIX] Fix deprecation

- netneurotools/stats.py
Model R2s for dominance analysis are now computed in parallel
> [ENH] added parallelization to dominance analysis function

- netneurotools/spatial/spatial_stats.py
This PR makes the `_morans_i_vectorized` function much faster by using `@` instead of `np.outer`
> [REF] Make _morans_i_vectorized much faster

- netneurotools/metrics/spreading.py
This commit adds to `netneurotools` functions to simulate atrophy spreading on brain networks with a SIR model. This is a python version of SIRsimulator, written by Ying-Qiu Zheng: https://github.com/yingqiuz/SIR_simulator
> [ENH] Add simulate_atrophy() + related functions

- docs/api.rst
- netneurotools/datasets/__init__.py
- netneurotools/datasets/fetch_project.py
- netneurotools/datasets/netneurotools.bib
- netneurotools/datasets/references.json
- netneurotools/interface/surf_parc.py
- netneurotools/modularity/modules.py
This Pull Request adds a `fetch_bazinet_assortativity` function. 
It also incorporates a few minor changes:
- It adds a reference to the docstring of the `fetch_hansen_manynetworks` function.
- It fixes a `ValueError` in `get_modularity_z`, fixing issue [#148](https://github.com/netneurolab/netneurotools/issues/148). 
- It fixes an issue in `parcels_to_vertices` where np.nan values were converted to the lowest possible integer values when the type of the parcellated data was `int`
> [ENH] Add fetch_bazinet_assortavity + a few minor changes
