netneurotools/networks.py

When there was no connection for a given distance bin the function errored out even though it should just ignore it and continue on.

[FIX] Fixes error in struct_consensus()

---

netneurotools/__init__.py
netneurotools/plotting.py
netneurotools/utils.py

Adds `netneurotools.plotting.plot_fsaverage()` function (and helper utility function) for plotting parcellated surface data to surface projection using PySurfer.

[ENH] Adds FreeSurfer surface plotting function

---

docs/api.rst
docs/conf.py
netneurotools/__init__.py
netneurotools/metrics.py
netneurotools/networks.py
netneurotools/plotting.py
netneurotools/stats.py
netneurotools/tests/__init__.py
netneurotools/tests/utils.py
netneurotools/utils.py

Sooooo this definitely should have been more than one commit, totally my bad.
Pretty large documentation update (examples in the docstrings! better docstrings!), with a few added functions from other projects I'd worked on.

[DOC] Updated documentation and API reference

---

.travis.yml
environment.yml
netneurotools/datasets/datasets.py
netneurotools/info.py
requirements.txt

Adds support for conda installation and general revamp of testing structure.

[TEST] Updates Travis CI

---

netneurotools/datasets/__init__.py
netneurotools/datasets/datasets.py
netneurotools/datasets/utils.py
netneurotools/freesurfer.py
netneurotools/plotting.py
netneurotools/tests/test_datasets.py

Includes minor dataset fetcher, updates to `plotting.plot_fsaverage()`, and a new center-of-mass calculation function to be used with `stats.gen_spinsamples()`.

[ENH] Adds functions for working w/FreeSurfer's fsaverage

---

netneurotools/stats.py

Forces all inputs to numpy arrays

[ENH] Adds type coercion to stats.residualize()

---

netneurotools/stats.py

Adds the optional kwarg `exact` to `stats.gen_spinsamples()`, which allows user to specify whether each coordinate location must be uniquely re-assigned for every rotation. This diverges from the traditional
implementation of the spin test by Alexander-Bloch et al., but may be a desired feature when using nodal/regional parcellations rather than vertices.

[ENH] Adds exact matching in stats.gen_spinsamples

---

netneurotools/stats.py
netneurotools/utils.py

Refactors nntools.stats.gen_spinsamples() to attempt to avoid generation
of duplicate resamples.

[FIX] Fixes duplicate spintests resamples

---

.gitignore
docs/Makefile
docs/_static/theme_overrides.css
docs/_templates/function.rst
docs/api.rst
docs/conf.py
docs/index.rst
docs/requirements.txt
examples/README.txt
examples/plot_consensus_clustering.py
examples/plot_spin_test.py
netneurotools/cluster.py
netneurotools/modularity.py
netneurotools/plotting.py
netneurotools/tests/test_cluster.py

With some fun new functions for working with different clustering partitions! 
Also includes some light refactoring of `nntools.modularity` to use the new `find_consensus()` function.
**To do:**

[ENH] Adds cluster submodule

---

docs/conf.py
environment.yml
examples/plot_consensus_clustering.py
netneurotools/datasets/mirchi.py
netneurotools/freesurfer.py
netneurotools/info.py
netneurotools/plotting.py
netneurotools/utils.py
requirements.txt

Remove `pandas`, `requests`, and `seaborn` as requirements throughout package and modify all content to avoid using them.

[REF] Reduce required dependencies

---

netneurotools/plotting.py

Now performs more-or-less the same functionality, but seaborn isn't a required dependency!

[REF] Removes seaborn in plotting.plot_mod_heatmap

---

docs/api.rst
docs/conf.py
examples/plot_mirchi_2018.py
netneurotools/datasets/__init__.py
netneurotools/info.py
netneurotools/plotting.py
requirements.txt

With sphinx gallery example, etc

[ENH] Adds Mirchi et al., 2018, SCAN replication

---

examples/plot_mirchi_2018.py
netneurotools/datasets/mirchi.py

Lower number of bootstraps, don't reset random seed. WHY IS SVD CONVERGENCE FAILING!? :man_facepalming:

[REF] Attempt to fix Mirchi 2018 example

---

netneurotools/info.py

Add Zhen-Qi to info.py

---

examples/plot_mirchi_2018.py

To reflect the recent changes I carelessly made via the GitHub UI (i.e., reducing the number of bootstraps and permutations run, which were referenced in the code comments).

[DOC] Updates docs in Mirchi example

---

netneurotools/plotting.py

Closes #50.
The `noplot` parameter accepts a list of parcel names that should not be plotted. By default, 'corpuscallosum' and 'unknown' are included in this list (due to their inclusion in all default FreeSurfer parcellations), but additional regions can be added.
Also allows plotting to arbitrary subjects (not just `fsaverage`) via the `subject` parameter.

[ENH] Adds `noplot` param to plot_fsaverage()

---

.travis.yml
dev_environment.yml
docs/api.rst
docs/requirements.txt
examples/plot_perm_pvals.py
netneurotools/stats.py
netneurotools/tests/test_stats.py
setup.cfg

Works well with `stats.gen_spinsamples`! Once this is done I'll work on updating that example.
To Do:

[ENH] Adds permutation tests for correlations

---

netneurotools/plotting.py

Added the 'order' argument (can be either 'LR' or 'RL'), and function will split the data accordingly

[ENH] Added 'order' argument

---

netneurotools/freesurfer.py
netneurotools/stats.py
netneurotools/tests/test_freesurfer.py

Including an implementation of https://github.com/frantisekvasa/rotate_parcellation, and two new methods for FreeSurfer data.

[ENH] Adds spatial permutation methods for parcellated data

---

netneurotools/plotting.py

Updates the NaN color from "dark red" to "gainsboro" in plot_conte69

[ENH] Updates the NaN color in mayavi for plot_conte69

---

netneurotools/freesurfer.py
netneurotools/tests/test_freesurfer.py

Including allowing 2D data in `parcels_to_vertices` and `vertices_to_parcels` and accepting pre-computed spins in `spin_data`,

[REF] Updates FreeSurfer-related spin test functionality

---

docs/conf.py
netneurotools/plotting.py

Closes #70 .
Also a minor change to sphinx-gallery builds.

[FIX] Better path finding in nnplot.plot_fsaverage()

---

docs/api.rst
netneurotools/datasets/fetchers.py
netneurotools/freesurfer.py
netneurotools/stats.py
netneurotools/tests/test_datasets.py
netneurotools/tests/test_freesurfer.py

Adds new method for calculating parcel centroids on the surface.
Also updates a bunch of other `netneurotools.freesurfer` functionality and adds some functions to the API reference / docs.

[ENH] Surface centroid calculation

---

netneurotools/plotting.py

Allows providing extra kwargs to `plot_fsaverage()` that will be passed through to `surfer.Brain`

[REF] Pass through kwargs to plot_fsaverage

---

netneurotools/plotting.py

Adding features to `plot_mod_heatmap`
- square: making the matrix equal aspect
- ticklabels: labels for every region

[ENH] add features to plot_mod_heatmap

---

.travis.yml
netneurotools/freesurfer.py
netneurotools/surface.py

Uses more accurate surface graph construction to better estimate geodesic parcel centroids in `nnsurf.find_parcel_centroids()`.

[ENH] Improves geodesic parcel centroids

---

netneurotools/plotting.py

Added data_kws argument to plot_fsaverage in plotting.py.

[ENH] Added data_kws argument to plot_fsaverage

---

.github/workflows/tests.yml
netneurotools/plotting.py
netneurotools/tests/test_plotting.py
tools/install_dependencies.sh
tools/run_checks.sh

For plotting vertex-level data using pysurfer. Also refactors `plot_fsaverage()` so that after initial input formatting it calls `plot_fsvertex()` under the hood.
@VinceBaz since you've worked on `plot_fsaverage()` before maybe you could take a look at this (to make sure it makes sense) and ensure I didn't screw up anything too dramatically with my refactoring? If you're not working on anything that would be able to test the new `plot_fsaverage()` at the moment then no worries.

[ENH] Creates plot_fsvertex() function

---

docs/api.rst
netneurotools/stats.py
requirements.txt

I have the dominance stats snippet here! Alpha stage -- major changes are very welcomed!

[ENH] Added dominance stats function

---

netneurotools/stats.py

Just realized this was not the same 😱
https://github.com/netneurolab/netneurotools/pull/97#discussion_r571301858

[FIX] Fix bug in dominance analysis function

---

netneurotools/data/osf.json
netneurotools/datasets/__init__.py
netneurotools/datasets/fetchers.py
netneurotools/plotting.py
netneurotools/tests/test_datasets.py

I added a plot_fslr() function, which basically is a generalization of the plot_conte69() function. This function asks the user which surface atlases he wants to use. For human brains, this atlas will more often than not be the conte69 atlas. For macaque, however, other atlases exist. One of these atlases is the Yerkes19 atlas (Donahue et al., 2016, J. Neurosci.).
I also added a fetcher function: fetch_yerkes19() to download this Yerkes19 atlas.

Added plot_fslr() function and a yerkes19 fetcher

---

docs/Makefile
docs/api.rst
docs/conf.py

[DOC] Update docs

---

netneurotools/metrics.py

Oooops! Just to make it exactly the same as the original.

[FIX] Fix function naming

---

docs/api.rst
docs/conf.py
netneurotools/metrics.py
netneurotools/plotting.py
netneurotools/stats.py
pyproject.toml

Adding some new stats functions. Most of them are numba-optimized, but also works without numba. 
They'll ultimately be part of Andrea's toolbox. 
I'm putting the alpha versions here so we can test them & be early adopters. 
- network_pearsonr
- network_pearsonr_numba
- network_pearsonr_pairwise
- effective_resistance
- network_polarisation
- network_variance
- network_variance_numba
- network_covariance
- network_covariance_numba

[ENH] New stats functions

---

netneurotools/metrics.py

Fixing the asymmetric case in search_information and allowing for directed graphs in distance_wei_floyd.

[FIX] fixing the asymmetric case in search_information

---

docs/api.rst
netneurotools/spatial/__init__.py
netneurotools/spatial/spatial_stats.py
netneurotools/spatial/tests/test_spatialstats.py

[FIX] rename Lee's L functions

---

netneurotools/datasets/datasets.json
netneurotools/metrics/bct.py
netneurotools/plotting/pyvista_plotters.py

This commit adds a new fetch function for the [bazinet_assortativity](https://github.com/netneurolab/bazinet_assortativity) repository. It also updates the fetch function for the hansen_many_networks repository.

[ENH] Added new fetch function for bazinet_assortativity + other minor changes
